name = "astrodev/cardanocasino"
version = "1.2.1"
compiler = "v1.1.10"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'astrodev/cardanocasino'"

[repository]
user = "astrodev"
project = "cardanocasino"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[config]
